name: machinelearning_samples
channels:
  - defaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - scikit-learn
  - pip
  - pandas
  - pylint
  - yapf
  - tensorflow=2.18.1
  - gym
  - keras